name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven

      - name: Set environment variables
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        run: |
          echo "MAIL_USERNAME=${MAIL_USERNAME}" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=${MAIL_PASSWORD}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
